version: "3.8"
services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: pharmacy-backend
    ports:
      - "5000:5000"
    networks:
      - pharmacy_network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: pharmacy-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - pharmacy_network

networks:
  pharmacy_network:
    driver: bridge
