apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmacy-frontend
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: pharmacy-frontend
  template:
    metadata:
      labels:
        app: pharmacy-frontend
    spec:
      containers:
      - name: frontend
        image: icr.io/pharmaapp/pharmacy-frontend:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: cloud-secret
---
apiVersion: v1
kind: Service
metadata:
  name: pharmacy-frontend
spec:
  selector:
    app: pharmacy-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
